### ISSUE TITLE
when css modules use `:export {}` is not work

### ISSUE THREAD

**Issue by baranwang** [mrmckeb/typescript-plugin-css-modules#128]
**Describe the bug**
when css modules use `:export {}` is not work

**To Reproduce**
```scss
.foo { }

:export {
 bar: 'xxx'
}
```
 it's not work, get `let styles: {}`

**Expected behavior**
```
let styles: {
 foo: string,
 bar: string
}
```

sorry, my English is poor, hope to understand :)
