### ISSUE TITLE
CSS Animations doesn't work

### ISSUE THREAD

**Issue by jcubic** [mrmckeb/typescript-plugin-css-modules#154]
**Describe the bug**
There is no way to use CSS animations (keyframes).

**To Reproduce**

Example code:

```css
.loader::before {
  content: "";
  display: block;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%) rotate(0deg);
  width: 30px;
  height: 30px;
  border: 6px solid #aaa;
  border-radius: 50%;
  border-top-color: #005596;
  animation: 1s rotate linear infinite;
}
@keyframes rotate {
  to {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
```

```jsx
import { loader } from "./style.module.css";

export default function Spinner() {
  return <div className={loader}></div>;
}
```

The output CSS look like this:

```css
_src_components_Spinner_style_module__loader::before {
    content: "";
    display: block;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%) rotate(0deg);
    width: 30px;
    height: 30px;
    border: 6px solid #aaa;
    border-radius: 50%;
    border-top-color: #005596;
    animation: 1s :local(rotate) linear infinite;
}
```
Which is invalid CSS.

**Expected behavior**
Animations should work

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Fedora GNU/Linux
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 99

**Smartphone (please complete the following information):**

**Additional context**
I'm using Codesandbox with the TypeScript+ReactJS project.
Here is a link to my [codesanbox project](https://codesandbox.io/s/react-router-remote-table-demo-forked-ur65tf?file=/src/components/Spinner/style.module.css).
