### ISSUE TITLE
SCSS Property does not exist on type '{}'

### ISSUE THREAD

**Issue by jerryc05** [mrmckeb/typescript-plugin-css-modules#188]
1. enable `"goToDefinition": true` in `tsconfig.json`

2. create a sample `index.scss` file look like this:
```scss
.classA {
  height: 100%;
  &>.classB {
    width: 100%;
  }
}
```

3. in a typescript file, import the scss as `import css from './index.scss'` 

4. after import, only `css.classA` is valid. accessing `css.classB` gives 
```
Property 'classB' does not exist on type 'typeof import("???/index.scss")'
```

5. However, turning `goToDefinition` off makes `classB` valid, but I would like to keep it on and still be able to use `css.classB`
