### ISSUE TITLE
using multiple `&` causes exported type to be {}

### ISSUE THREAD

**Issue by GideonMax** [mrmckeb/typescript-plugin-css-modules#194]
**Describe the bug**
when using multiple ampersands (to increase selector specificity), the exported type is {}
example:

the exported type in this example is {}.

**To Reproduce**
make scss file with multiple ampersand on some property for specificity, for example:
```scss
.example-class {
    &&& {
        visibility: hidden;
    }
}
// even other classes are affected
.other-class {
   color: red;
}
```
the exported type will be {}

**Expected behavior**
the exported type should be accurate.
In this example: Record<"example-class"|"other-class",string> or something equivalent

**Screenshots**
![css](https://user-images.githubusercontent.com/45212668/215328592-2640e6a2-552b-4953-a983-2c0ed9f4ed17.png)
![ts](https://user-images.githubusercontent.com/45212668/215328609-94ffaef3-1b47-4c18-91ed-acccae18d364.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 
    Chrome version: 109.0.5414.119
    plugin version: 4.1.1 (latest as of writing)
